### ISSUE TITLE
Set up QA server

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/dlp-curate#1]
- [x] Build Ubuntu 18.04 server for dlp-curate project in DCE Hosting AWS
- [x] Cantaloupe is installed on the same system using the IIIFy code

**Comment by bess** [comment]
FYI, looks like they are expecting mysql. We can roll with that, we did it for UCLA, but it's a not our standard build, and I'm hitting a few other bumps (e.g., upgrading to bundler 2) so this is taking longer than I'd hoped it would.

**Comment by bess** [comment]
![cantaloupe_on_curate-qa.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/b56fc02e-b42b-455e-87d2-602ee3c68c44)

**Comment by bess** [comment]
https://curate-qa.curationexperts.com/cantaloupe/iiif/2 seems to be working

Hard to tell exactly w/out the ability to load images, though
