### ISSUE TITLE
Make sure we have VPN connections

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/dlp-curate#10]
We are set up with Emory VPN connections
- [x] Mark
- [x] Bess
- [x] Jamie

**Comment by bess** [comment]
Collin says:
* Instructions here: http://it.emory.edu/vpntools/access.html
* Success looks like signing into F5, and loading curate.library.emory.edu
￼￼￼￼￼

**Comment by mark-dce** [comment]
Looks like I can get to curate.library.emory.edu, but they're having deployment issues - I'm getting an error page that looks like a passenger load issue.
