### ISSUE TITLE
Re-brand darlingtonia

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/dlp-curate#12]
- [x] Choose new name
- [x] Make a clone of darlingtonia with the new name
- [x] Update internal references to new name
- [x] Draft communication plan for https://github.com/curationexperts/darlingtonia/network/dependents
- [x] Create a DCE-deprecated organization
- [x] Move darlingtonia to DCE-deprecated org
- [x] Update readme
- [x] Publish the new gem on ruby gems
- [x] Set up CI for new repo

**Comment by RachelDCE** [comment]
Zizia is the name of our new gem.

**Comment by mark-dce** [comment]
https://www.perverdonk.com/wild%20flowers/Parsnip/Golden%20Alexanders/200808%20Golden%20Alexander%20(Zizia%20aurea)%20-%20NGS%20-%20the%20Book%20of%20Wild%20Flowers.htm

https://www.finegardening.com/plant/golden-alexander-zizia-aurea

**Comment by little9** [comment]
Dear `Institution`,

Our importer gem, Darlingtonia, is getting a new name and a new focus. Darlingtonia started as a command line importer tool, but in recent projects we have added UI that allows users to import directly form the Hyrax dashboard. To reflect this and other changes our importer gem will now be called Zizia. Accordingly, we are depreciating Darlingtonia and all future development will be done on Zizia. In the future, Zizia will not be compatible with Darlingtonia. The code for Darlingtonia will remain available at: `insert url here`, but no future development will be occurring.

**Comment by little9** [comment]
https://github.com/curationexperts/zizia
https://rubygems.org/gems/zizia
https://travis-ci.org/curationexperts/zizia
https://github.com/curationexperts-deprecated/darlingtonia

**Comment by bess** [comment]
This looks great! :D
