### ISSUE TITLE
Add UI components to new importer gem

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/dlp-curate#13]
- [x] Installing the importer gem also creates a UI to upload a CSV and start the import
- [x] Extract the upload UI from Tenejo into the new importer gem
- [x] Refactor Tenejo to remove the local UI and use the import UI from the gem
- [x] Add the new UI to dlp-curate
- [x] Decide if we do a generator or a mountable engine.

**Comment by little9** [comment]
Adding the UI to `dlp-curate` is blocked until collections starting working. The UI assumes that
you are adding the items to a collection and their current collection model is not able to 
be saved.
