### ISSUE TITLE
Describe baseline infrastructure (CPUs, RAM, etc)

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/dlp-curate#15]
- [x] Add the current system specs to the wiki page at https://github.com/curationexperts/in-house/wiki/dlp-curate.

**Comment by mark-dce** [comment]
See https://github.com/curationexperts/in-house/wiki/dlp-curate#environments

<img width="738" alt="image" src="https://user-images.githubusercontent.com/3064318/61984847-b74cdb00-afcb-11e9-8cb5-61872aea53c7.png">
