### ISSUE TITLE
SPIKE: Log background jobs

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/dlp-curate#19]
- [x] Identify 3 options for logging background jobs
- [x] List pros and cons of each
- [x] Decide on one to try

**Comment by little9** [comment]
If we don't jobs associated with the parent job there is already logging from how long a job takes. 
The done log entry for a job looks like this:

`2019-07-23T01:48:27.686Z 1233 TID-phm55 CreateDerivativesJob JID-adafd7830d8255e0bf7d4451 INFO: done: 41.29 sec`

I set up some fields in Splunk to work with the existing logs, so to find all the jobs a certain type on a host: 
`host="etd.library.emory.edu" JobName="CharacterizeJob"`

Here's an example chart that shows the average time the `CreateDerivativesJob` takes:
https://prd-p-h3smll3m3c5l.cloud.splunk.com/en-US/app/search/search?q=search%20host%3D%22etd.library.emory.edu%22%20JobName%3D%22CreateDerivativesJob%22%7C%20timechart%20avg(job_time_to_complete)&earliest=0&latest=&display.page.search.mode=smart&dispatch.sample_ratio=1&display.page.search.showFields=1&display.page.search.tab=visualizations&display.general.type=visualizations&sid=1563832803.13747&display.visualizations.charting.chart=line&display.visualizations.type=charting

If we work from a stable set of data, we could use these existing logs & Splunk to measure if performance of the background jobs was improving or not.

**Comment by little9** [comment]
There are call backs which can be added to ApplicationJob:
https://github.com/emory-libraries/dlp-curate/blob/master/app/jobs/application_job.rb

https://api.rubyonrails.org/classes/ActiveJob/Callbacks/ClassMethods.html

`before_perform` and `after_perform` could be used to add
additional logging. 

The problem with that is that you can only access the 
arguments passed to the job. There isn't a way to pass in
information about what `Work` the job is for. 

The Job name and how long it took to complete are already being logged
so I'm not sure what other useful information could added this way.

There also isn't a way to determine the calling job for a job  here
without paying for Sidekiq or investing several weeks in writing 
low level Redis code: https://stackoverflow.com/questions/30401674/sidekiq-activejob-track-spawned-jobs-in

A pro of doing that is that we could sell an alternative to Sidekiq Pro :)

**Comment by little9** [comment]
@mhbussey Here are the options identified by Bess and me:
1. Override all jobs and and actors and have them record a status 
- Con: Will be time intensive and distance the app from mainline Hyrax
- Con: There were performance problems doing this on the UCLA servers. (There will need to be a lot of database connections available)
- Pro: Avoids paying for Sidekiq Pro
2. Run all jobs inline 
-  Con: Doesn't take advantage of multiple threads and ability to retry jobs
- Con: Maybe we'll need to override to add the logging regardless of how the jobs are run?
3. Use Sidekiq Pro
- Pro: Provides a way to see the status of a parent job and all the child jobs (with UI)
- Con: $950 a year
