### ISSUE TITLE
SPIKE: How should we authenticate on curate-qa.curationexperts.com?

### ISSUE THREAD

**Issue by bess** [curationexperts/dlp-curate#25]
We either need to:

1. Get permission to authenticate against Emory's shibboleth

OR

2. Be able to use database authentication in production mode

**Comment by bess** [comment]
You're supposed to be able to set `export DATABASE_AUTH=true` to switch to database authentication. I've tried that in `.env.production` and in `/etc/profile` and it didn't work in either place. Maybe something else is needed to get that working in production mode?

**Comment by bess** [comment]
I talked to Colin and he said they expect the system to use shibboleth auth in production mode. He pointed me to Solomon for advice on how to do that.

Solomon thinks we will be better off authenticating against our local shibboleth system than getting access to Emory.

**Comment by RachelDCE** [comment]
Decided to authenticate to DCE's shibboleth
