### ISSUE TITLE
Set up continuous integration service

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/dlp-curate#3]
- [x] Configure our ci system of choice to run test suite whenever new code is committed to github

**Comment by little9** [comment]
https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/

Enabling CI for forked pull requests
Now, we’d like to enable this same workflow for pull requests originating from forked repositories. Not only does this allow proposed changes from contributors without commit access , but it’s also helpful for committers who prefer to work from their own forks.

There is a setting to turn on builds from forks in CircleCI, we should ask someone from Emory to turn this on. That way we don't have to change anything in the codebase on our fork.

**Comment by bess** [comment]
I had a phone call with Collin and between the two of us we got all the settings fixed. It's running now (although my branch isn't passing): 


![circle_ci_running.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/b397d924-aa38-4e65-94f1-82c1c17f2bfb)
