### ISSUE TITLE
YELLOWBACKS: Import updates to handle complex structures (Volumes, Books, Pages)

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/dlp-curate#32]
Given a manifest file with the structure of a complex yellow back (volumes + pages), update the importer to create works that reflect the expected hierarchy in dip-curate.

NOTE: This story partially fulfills the requirements of Emory Epic [291](https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/291)

**Comment by eporter23** [comment]
Current documentation for Yellowbacks:

Reference object in Emory's Curate (incomplete pages)
SIP mapping
"Pull-list" spreadsheet
Alma
