### ISSUE TITLE
LANGMUIR: Work Display

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/dlp-curate#36]
Update the single item display page as necessary to validate the import process.

NOTE: additional display updates may be required or desired to support functionality not related to import. The scope of this ticket is only to ensure works created by the importer have been successfully imported and the expected metadata is present.

**Comment by eporter23** [comment]
@mark-dce here is a check I did on Curate fields that are missing from work pages' display, though I know at this point we only need to focus on those populated for Langmuir: https://docs.google.com/spreadsheets/d/1cTTrtqWZRGHTjY8ZP2GvJokUl6IkxxscXj8aTg2D5P4/edit?usp=sharing
