### ISSUE TITLE
Set up developer environments

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/dlp-curate#5]
Ensure we can run the test suite locally.
- [x] Bess
- [x] Jamie
- [x] Mark

**Comment by bess** [comment]
FYI, I had to run `gem update --system` before `bundle install` would work for me on this. I had run into the problem described in this StackOverflow thread: https://stackoverflow.com/questions/47026174/find-spec-for-exe-cant-find-gem-bundler-0-a-gemgemnotfoundexception

**Comment by mark-dce** [comment]
I ran into a couple issues:

1. The curate-dlp readme says I can run `bin/rails ci` but I don't see any CI task defined
1. I needed to run `yarn install --check-files` before I could successfully run `db:migrate`
1. The the test suite requires redis to be running - not a problem - but not stated explicitly anywhere (could we just add a before check that redis, solr, and fedora are running?  would this help newbies avoid or at least notice some setup error states?)
