### ISSUE TITLE
Team teachout on Hyrax 3.0 vanilla metadata

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/dlp-curate#7]
- [x] Generate a  Hyrax 3.0.0 beta 1 application 
- [x] Generate a generic worktype 
- [x] Review the provided metadata fields
- [x] Compare to Hyrax 2.x 
 Bonus
- [x] Compare to dlp-curate

**Comment by little9** [comment]
Hyrax 3 includes `Hyrax::BasicMetadata` in the same way as Hyrax 2 except for the addition of the 
`rights_note` property. See https://github.com/samvera/hyrax/commit/26b2b09e62d5ec15185f46f78f1bb058fd5269df#diff-95f58fca8363dde3858abd50f642dc0c

`Hyrax::BasicMetadata` was removed by Emory in `dlp-curate`. See:  https://github.com/emory-libraries/dlp-curate/commit/9599e672b90cb097616eac1d7de8730ed2ce6f4d#diff-89cb54638ef3872c82caa3cf616b8f47
